name: Build

on: [push]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      REPO_DIR: 'dlib'
      BUILD_COMMIT: 'v19.24.1'
      DLIB_BIN_VERSION: '19.24.1'
      CIBUILDWHEEL_VERSION: '2.11.4'
      CIBW_BEFORE_BUILD: 'pip install cmake'
      CIBW_BUILD: 'cp37-* cp38-* cp39-* cp310-* cp311-*'
      CIBW_SKIP: '*musllinux*'
      CIBW_ARCHS: 'auto64'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        shell: bash
        run: |
          git submodule update --init --recursive
          git -C dlib checkout $BUILD_COMMIT

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install cibuildwheel
        shell: bash
        run: python -m pip install cibuildwheel==$CIBUILDWHEEL_VERSION
      
      - name: Build wheels
        shell: bash
        run: python3 -m cibuildwheel $REPO_DIR --output-dir wheelhouse

      - name: Save wheels
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_to_github:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.whl"
          tags: true
          draft: true
